-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 00:19:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
    'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sportswearshop2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sportswearshop2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportswearshop2` DEFAULT CHARACTER SET utf8;
USE `sportswearshop2`;

-- -----------------------------------------------------
-- Table `sportswearshop2`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswearshop2`.`product_category`
(
  `category_id` BIGINT(20)  NOT NULL,
  `name`        VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `id_UNIQUE` (`category_id` ASC) VISIBLE
);


-- -----------------------------------------------------
-- Table `sportswearshop2`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswearshop2`.`product`
(
  `product_id`   BIGINT(20)    NOT NULL,
  `name`         VARCHAR(45)   NOT NULL,
  `brand`        VARCHAR(45)   NOT NULL,
  `category_id`  BIGINT(20)    NOT NULL,
  `price`        DECIMAL(10)   NULL DEFAULT NULL,
  `color`        VARCHAR(45)   NULL DEFAULT NULL,
  `size`         VARCHAR(45)   NULL DEFAULT NULL,
  `description`  VARCHAR(5000) NULL DEFAULT 'NULL',
  `image`        LONGBLOB      NULL DEFAULT NULL,
  `out_of_stock` INT           NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  UNIQUE INDEX `id_product_UNIQUE` (`product_id` ASC) VISIBLE,
  INDEX `fk_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_product`
    FOREIGN KEY (`category_id`)
      REFERENCES `sportswearshop2`.`product_category` (`category_id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table `sportswearshop2`.`office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswearshop2`.`office`
(
  `firstname` VARCHAR(45) NOT NULL,
  `lastname`  VARCHAR(45) NOT NULL,
  `country`   VARCHAR(45) NOT NULL,
  `city`      VARCHAR(45) NOT NULL,
  `email`     VARCHAR(45) NULL DEFAULT NULL,
  `phone`     VARCHAR(45) NOT NULL,
  `user_id`   BIGINT(20)  NOT NULL,
  `orders`    BIGINT(20)  NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`)
);


-- -----------------------------------------------------
-- Table `sportswearshop2`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswearshop2`.`user`
(
  `user_id`  BIGINT(20)  NOT NULL,
  `login`    VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `roles`    VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  CONSTRAINT `fk_office_user`
    FOREIGN KEY (`user_id`)
      REFERENCES `sportswearshop2`.`office` (`user_id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table `sportswearshop2`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswearshop2`.`role`
(
  `role_id` BIGINT(20)  NOT NULL,
  `name`    VARCHAR(45) NOT NULL,
  `users`   VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `id_UNIQUE` (`role_id` ASC) VISIBLE
);


-- -----------------------------------------------------
-- Table `sportswearshop2`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswearshop2`.`cart`
(
  `cart_id`     BIGINT(20)  NOT NULL,
  `sum`         DECIMAL(20) NULL DEFAULT NULL,
  `products_id` BIGINT(20)  NOT NULL,
  `quantity`    INT         NULL DEFAULT NULL,
  UNIQUE INDEX `id_UNIQUE` (`cart_id` ASC) VISIBLE,
  INDEX `fk_product_id_idx` (`cart_id` ASC) VISIBLE,
  PRIMARY KEY (`cart_id`, `products_id`),
  CONSTRAINT `fk_product_cart`
    FOREIGN KEY (`products_id`)
      REFERENCES `sportswearshop2`.`product` (`product_id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table `sportswearshop2`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswearshop2`.`order`
(
  `order_id`  BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `date_time` TIMESTAMP(6) NOT NULL,
  `sum`       DECIMAL(10)  NULL DEFAULT NULL,
  `payment`   BINARY(2)    NOT NULL,
  `cart_id`   BIGINT(20)   NOT NULL,
  `user_id`   BIGINT(20)   NULL DEFAULT NULL,
  INDEX `fk_cart_order_idx` (`cart_id` ASC) VISIBLE,
  PRIMARY KEY (`order_id`),
  INDEX `fk_office_order_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_order`
    FOREIGN KEY (`cart_id`)
      REFERENCES `sportswearshop2`.`cart` (`cart_id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  CONSTRAINT `fk_office_order`
    FOREIGN KEY (`user_id`)
      REFERENCES `sportswearshop2`.`office` (`user_id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table `sportswearshop2`.`user_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportswearshop2`.`user_has_role`
(
  `user_user_id` BIGINT(20) NOT NULL,
  `role_role_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`user_user_id`, `role_role_id`),
  INDEX `fk_user_has_role_role1_idx` (`role_role_id` ASC) VISIBLE,
  INDEX `fk_user_has_role_user1_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY (`user_user_id`)
      REFERENCES `sportswearshop2`.`user` (`user_id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_role_id`)
      REFERENCES `sportswearshop2`.`role` (`role_id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
